#baseURL = "https://f3rnandez57.github.io/my_blog/"
languageCode = "en"
title = "F3rNaNDEZ57's Tech Hub"
theme = "github-style"
googleAnalytics = "UA-123456-789"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "Kavindu Fernando"
  description = "Python Dev,IOT,Problem Solver"
  github = "F3rNaNDEZ57"
  facebook = "profile.php?id=100086076716793&mibextid=LQQJ4d"
  twitter = "#"
  linkedin = "fernando-kavindu"
  instagram = "k_fer_nando"
  email = "kavindufernando329@gmail.com"
  url = "https://f3rnandez57.github.io/my_blog/"
  keywords = "blog, google analytics,problem solving,data structures,algorithms"
  rss = false
  lastmod = true
  userStatusEmoji = "😀"
  favicon = "/images/github.png"
  location = "Sri Lanka"
  enableGitalk = false

  [params.gitalk]
    clientID = "Your client ID" 
    clientSecret = "Your client secret" 
    repo = "repo"
    owner = "MeiK2333"
    admin = "MeiK2333"
    id = "location.pathname"
    labels = "gitalk"
    perPage = 15
    pagerDirection = "last"
    createIssueManually = true
    distractionFreeMode = false


[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]